language: objective-c

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
  - brew tap --repair

env:
  - PACKAGE=adbs

script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
